### ISSUE TITLE
return selected points

### ISSUE THREAD

**Issue by sahilseth** [AliciaSchep/gglabeller#1]
This is a really useful package. I was wondering if it is possible to return the row names of the selected points to throw them into another function for misc. operations?

Also, do you know if R supports the use of a lasso tool for selection?

Thanks!!

**Comment by AliciaSchep** [comment]
For the row.names, the function does not return the row names but it does return the indices of the rows, which you could use to pull out the rownames.

```r
library(gglabeller)
library(ggplot2)
library(ggrepel)
 
p <- ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point() + 
+     theme_classic(base_size = 18)
gglabeller_example <- gglabeller(p, aes(label = rownames(mtcars)))
rownames(mtcars)[gglabeller_example$ix] # This would give the names
```
The function returns a list with three components, one is the plot, another is the indices of the rows, and the other is a code snippet that can reproduce the plot.  

As for lasso selection, there are likely some htmlwidgets that support lasso selection (e.g. plotly).  In terms of interacting with a plot from ggplot2 in shiny (what is done within this package), I am not aware of a way to select points via lasso.
