### ISSUE TITLE
Closing the Shiny from R in terminal

### ISSUE THREAD

**Issue by Fred-White94** [AliciaSchep/gglabeller#4]
On closing the app by clicking the cross it leaves the terminal in a constant state of R working at 100%.
Just stuck at the stage as if the app was still open, is there a fix or a way out of this?

Cheers

**Comment by AliciaSchep** [comment]
As you closed the issue, I assume you resolved it? If not, can you provide more info, e.g. a screenshot, the r version, what kind of terminal, etc

**Comment by Fred-White94** [comment]
Yeah sorry, I jumped the gun on logging the bug.. works fine my dataset was just extremely large!
Cheers.
