### ISSUE TITLE
Using gglabeller with geom_text_repel options for size and fontface

### ISSUE THREAD

**Issue by sklucas** [AliciaSchep/gglabeller#5]
Hi Alicia,

Thanks for making such a great and useful package! I am trying to figure out how to modify the aesthetics of the label itself while using gglabeller (if this is pretty obvious, forgive me!). If I just use the ggrepel package to do my labelling, I can do this pretty easily using geom_text_repel, but I can't seem to figure out how to incorporate that with the utility gglabeller provides. Any insight would be helpful! 

Thank you,
Sarah

**Comment by AliciaSchep** [comment]
Hi Sarah,

Can you clarify a bit, e.g. by providing an example with geom_text_repel? 

If I am understanding your question correctly, the answer might be the "Parameters" tab in the gadget -- see the button at the bottom right.  That allows you to interactively select ggrepel parameters.  You should also be able to pass ggrepel parameters to gglabeller (and then you can refine using the Parameters tab).  If you encounter any specific issues with that, please update!

**Comment by AliciaSchep** [comment]
Just read the title -- now I think I have a better idea.  I think that is currently missing functionality, as only the named arguments from geom_text_repel (and not ... arguments to ggrepel) are able to be passed in via gglabeller or edited with parameters as described above (i.e. what was described above would apply to editing segment.color but not fontface).  I'll explore adding this capability. 

 In the meantime, one of the outputs of the app is a code snippet for recreating the plot.  That code snippet will have a call to geom_text_repel that can be manually edited to include extra arguments.

**Comment by AliciaSchep** [comment]
@sklucas -- just pushed a new version of gglabeller that should enable adding fontface or color or other optional arguments to geom_text_repel or geom_label_repel, e.g. with README example:

```r
gglabeller(p, aes(label = rownames(mtcars)),  fontface = "bold", color = "red")
```

**Comment by sklucas** [comment]
Amazing. Thanks Alicia! I know it was a little aesthetic request, but it definitely helps a great deal!
