### ISSUE TITLE
only works on first element of list of plots

### ISSUE THREAD

**Issue by Aariq** [AliciaSchep/gglabeller#6]
If I create a list of plots with map(), I'm unable to select points when gglabeller is called on any element of that list but the first.  The GUI still pops up, and I can still use the "Label All" button, but brushing over points doesn't label them.

```
library(tidyverse)
library(gglabeller)

#Create some data
testdata <- tibble(sample = rep(LETTERS[1:6], each = 15),
                   catvar = rep(paste0("var_",letters[1:15]), times = 6),
                   contvar = abs(rnorm(90)))

#Split data into manageable chunks for plotting by categorical variables
testlist <- testdata %>%
  mutate(catvar = as.factor(catvar),
         group = as.numeric(catvar) %>%
           cut(3) %>% #cut into how many pieces?
           as.integer()) %>% 
  split(.$group) #returns a list of dataframes

testplots <- map(testlist, #for every data frame in the list...
                 ~ggplot(., aes(x = catvar, y = contvar, label = sample)) +
                   geom_point()
)
gglabeller(testplots[[1]])
gglabeller(testplots[[2]])
```

**Comment by AliciaSchep** [comment]
Weird! Thanks for sharing a reproducible example -- I see the same behavior with your code.  

The issue also arises with:

```r
testplot <- ggplot(testlists[[2]], aes(x = catvar, y = contvar, label = sample)) +
                   geom_point()
gglabeller(testplot)
```
So the issue seems to be with a plot made using a dataframe created as above. 

It further appears that this issue is maybe more of an issue with nearPoints and brushPoints functions from shiny that are being used in this app, rather than a problem in the code for this app itself.  Using the[ basic example app from Shiny documentation on those functions](https://shiny.rstudio.com/articles/selecting-rows-of-data.html) but with the testlist data:

```r
library(tidyverse)
library(shiny)

#Create some data
testdata <- tibble(sample = rep(LETTERS[1:6], each = 15),
                   catvar = rep(paste0("var_",letters[1:15]), times = 6),
                   contvar = abs(rnorm(90)))

#Split data into manageable chunks for plotting by categorical variables
testlist <- testdata %>%
  mutate(catvar = as.factor(catvar),
         group = as.numeric(catvar) %>%
           cut(3) %>% #cut into how many pieces?
           as.integer()) %>% 
  split(.$group) #returns a list of dataframes

ui <- basicPage(
  plotOutput("plot1", click = "plot_click"),
  verbatimTextOutput("info")
)

server <- function(input, output) {
  output$plot1 <- renderPlot({
    ggplot(testlist[[2]], aes(x = catvar, y = contvar, label = sample)) +
      geom_point()
  })
  
  output$info <- renderPrint({
    nearPoints(testlist[[2]], input$plot_click, threshold = 10, maxpoints = 1,
               addDist = TRUE)
  })
}

shinyApp(ui, server)
```
There is no output when clicking if testlist[[2]] is used, but things work okay with testlist[[1]].  I will add an issue into the shiny repo...

**Comment by Aariq** [comment]
Thanks!  I had a feeling the problem was with the plot, not with gglabeller, but I don't know enough about Shiny to dig down and troubleshoot like that.

**Comment by AliciaSchep** [comment]
@Aariq Please see the work-around suggested in https://github.com/rstudio/shiny/issues/2052.  If in your plotting code you add `+ scale_x_discrete(drop = FALSE)`, the app works with the other plots as well.

**Comment by Aariq** [comment]
Thanks.  I see what's going on now.  I was able to fix this by `map()`ing a `mutate()` that applied `fct_drop()` to all the dataframes and now it works.

```
testlist <-  map(testlist, ~mutate(., catvar = fct_drop(catvar)))
```
