### ISSUE TITLE
Possible compatibility issue with ggplot2 v3.3.3

### ISSUE THREAD

**Issue by AidanQuinn** [AliciaSchep/gglabeller#7]
Hi, I've been using gglabeller for quite some time now and find it super helpful. However recently have been unable to use it because it throws the following error only when I try to click on a point:

`Warning: Error in : Aesthetics must be either length 1 or the same as the data (32): segment.colour 189:  <Anonymous>`

This error occurs whether I pass the labels through the gglabeller function or in the original ggplot2 object and I believe it coincided with upgrading to ggplot2 v3.3. It also occurs if I just pass a static label (single string). 

Reproducible _e.g._ is from your docs:

```
p <- ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point() + 
    theme_classic(base_size = 18)

gglabeller_example <- gglabeller(p, aes(label = rownames(mtcars)))

```

R.version:
```
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          0.1                         
year           2020                        
month          06                          
day            06                          
svn rev        78648                       
language       R                           
version.string R version 4.0.1 (2020-06-06)
nickname       See Things Now 
```

Any suggestions or thoughts?  Thank you for your help!

**Comment by AliciaSchep** [comment]
Thanks for the example, I can reproduce the issue.  Will look into a fix.
